### ISSUE TITLE
FaissIndexer build is broken

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina-hub#443]
**Problem**
When trying to bump FaissIndexer, this error shows up:

```          
         HubIO@31901[I]:E   ImportError: 
          HubIO@31901[I]:E   
          HubIO@31901[I]:E   IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
          HubIO@31901[I]:E   
          HubIO@31901[C]:E   Importing the multiarray numpy extension module failed.  Most
          HubIO@31901[C]:E   likely you are trying to import a failed build of numpy.
          HubIO@31901[I]:E   Here is how to proceed:
          HubIO@31901[I]:E   - If you're working with a numpy git repository, try `git clean -xdf`
          HubIO@31901[I]:E     (removes all files not under version control) and rebuild numpy.
          HubIO@31901[I]:E   - If you are simply trying to use the numpy version that you have installed:
          HubIO@31901[I]:E     your installation is broken - please reinstall numpy.
          HubIO@31901[I]:E   - If you have already reinstalled and that did not fix the problem, then:
          HubIO@31901[I]:E     1. Check that you are using the Python you expect (you're using /usr/local/bin/python),
          HubIO@31901[I]:E        and that you have no directories in your PATH or PYTHONPATH that can
          HubIO@31901[I]:E        interfere with the Python and numpy versions you're trying to use.
          HubIO@31901[I]:E     2. If (1) looks fine, you can open a new issue at
          HubIO@31901[I]:E        https://github.com/numpy/numpy/issues.  Please include details on:
          HubIO@31901[I]:E        - how you installed Python
          HubIO@31901[I]:E        - how you installed numpy
          HubIO@31901[I]:E        - your operating system
          HubIO@31901[I]:E        - whether or not you have multiple versions of Python installed
          HubIO@31901[I]:E        - if you built from source, your compiler versions and ideally a build log
          HubIO@31901[I]:E   
          HubIO@31901[C]:E        Note: this error has many possible causes, so please don't comment on
          HubIO@31901[I]:E        an existing issue about this - open a new one instead.
          HubIO@31901[I]:E   
          HubIO@31901[C]:E   Original error was: No module named 'numpy.core._multiarray_umath'
          HubIO@31901[I]:=========================== short test summary info ============================
          HubIO@31901[C]:ERROR tests/test_faissindexer.py
          HubIO@31901[C]:!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
          HubIO@31901[C]:=============================== 1 error in 0.15s ===============================
```
Trying to fix it following the principles in https://github.com/numpy/numpy/issues/12977#issuecomment-500232989
by having: 
```
RUN conda update -n base conda && \
    conda install -y -c pytorch faiss-cpu && \
    conda install -c anaconda setuptools && \
    conda install pip && \
    # https://github.com/numpy/numpy/issues/12977#issuecomment-500232989
    pip uninstall -y numpy && \
    conda install -y numpy && \
    pip install numpy
```

then there is an error with Grpc and ZMQ that according to https://github.com/jupyter/notebook/issues/3435#issuecomment-376894001 is a problem of mixing pip and conda install.

It fails at `--test-uses` step:

```
          HubIO@4543[I]:    collections.MutableSequence.register(BaseContainer)
          HubIO@4543[I]:
          HubIO@4543[W]:-- Docs: https://docs.pytest.org/en/stable/warnings.html
          HubIO@4543[W]:======================== 1 passed, 5 warnings in 8.32s =========================
          HubIO@4543[I]:Removing intermediate container 95b571a155ac
          HubIO@4543[I]: ---> 72e0e82d61ab
          HubIO@4543[I]:Step 9/9 : ENTRYPOINT ["jina", "pod", "--uses", "config.yml"]
          HubIO@4543[I]:
          HubIO@4543[I]: ---> Running in 334af07e849b
          HubIO@4543[I]:Removing intermediate container 334af07e849b
          HubIO@4543[I]: ---> 0749736b82d1
          HubIO@4543[I]:Successfully built 0749736b82d1
          HubIO@4543[I]:Successfully tagged jinahub/pod.indexer.faissindexer:0.0.7
          HubIO@4543[I]:building . takes 2 minutes and 43 seconds (163.42s)
          HubIO@4543[S]:🎉 built jinahub/pod.indexer.faissindexer:0.0.7 (sha256:0749736b82) uncompressed size: 1.5 GB
    equal_value@7458[I]:waiting ready signal from the container
    equal_value@7458[I]:JINA@ 1[E]:theses modules or classes can not be imported ['jina.executors.clients', 'jina.executors.encoders.tfserving']. You can use `jina check` to list all executors and drivers
    equal_value@7458[I]:Traceback (most recent call last):
    equal_value@7458[I]:File "/usr/local/bin/jina", line 8, in <module>
    equal_value@7458[I]:sys.exit(main())
    equal_value@7458[I]:File "/usr/local/lib/python3.7/site-packages/jina/main/__init__.py", line 57, in main
    equal_value@7458[I]:args = _get_run_args()
    equal_value@7458[I]:File "/usr/local/lib/python3.7/site-packages/jina/main/__init__.py", line 12, in _get_run_args
    equal_value@7458[I]:parser = get_main_parser()
    equal_value@7458[I]:File "/usr/local/lib/python3.7/site-packages/jina/main/parser.py", line 530, in get_main_parser
    equal_value@7458[I]:parser = set_base_parser()
    equal_value@7458[I]:File "/usr/local/lib/python3.7/site-packages/jina/main/parser.py", line 38, in set_base_parser
    equal_value@7458[I]:version=format_full_version_info(*get_full_version()),
    equal_value@7458[I]:File "/usr/local/lib/python3.7/site-packages/jina/helper.py", line 638, in get_full_version
    equal_value@7458[I]:import os, zmq, numpy, google.protobuf, grpc, ruamel.yaml
    equal_value@7458[I]:File "/usr/lib/python3/dist-packages/zmq/__init__.py", line 47, in <module>
    equal_value@7458[I]:from zmq import backend
    equal_value@7458[I]:File "/usr/lib/python3/dist-packages/zmq/backend/__init__.py", line 40, in <module>
    equal_value@7458[I]:reraise(*exc_info)
    equal_value@7458[I]:File "/usr/lib/python3/dist-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    equal_value@7458[I]:raise value
    equal_value@7458[I]:File "/usr/lib/python3/dist-packages/zmq/backend/__init__.py", line 27, in <module>
    equal_value@7458[I]:_ns = select_backend(first)
    equal_value@7458[I]:File "/usr/lib/python3/dist-packages/zmq/backend/select.py", line 27, in select_backend
    equal_value@7458[I]:mod = __import__(name, fromlist=public_api)
    equal_value@7458[I]:File "/usr/lib/python3/dist-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    equal_value@7458[I]:from . import (constants, error, message, context,
    equal_value@7458[I]:ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/usr/lib/python3/dist-packages/zmq/backend/cython/__init__.py)
    equal_value@7458[S]:terminated
    equal_value@4543[C]:fail to start <class 'jina.peapods.container.ContainerPea'> with name equal_value, this often means the executor used in the pod is not valid
          HubIO@4543[E]:can not use it in the Flow, please check your file bundle
          HubIO@4543[I]:deleting unused images
```

**Comment by JoanFM** [comment]
Closed by #459
